language: node_js
node_js:
  - lts/carbon
  - lts/dubnium
  - lts/erbium
  - stable
cache: npm
script:
  - npm run typecheck
  - npm run lint
  - npm run test -- --runInBand --coverage
after_success: cat coverage/lcov.info | npx coveralls
